---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен иметь мобильную версию
implicit:
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность редактировать содержимое корзины
  - Пользователь должен иметь возможность перелистывать страницы с товарами
  - Пользователь должен иметь возможность видеть рейтинг товарами
  - Пользователь должен иметь возможность поставить рейтинг товару, который купил
  - Пользователь должен иметь возможность оставить отзыв на товар, который купил
